#!/bin/bash

# Basic metadata
SHA=$(git rev-parse --short HEAD)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
DATE=$(git log -1 --format=%cd --date=short)
TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "untagged")

# Add '-dirty' flag if working tree isn't clean
if ! git diff-index --quiet HEAD --; then
    SHA="${SHA}-dirty"
    TAG="${TAG}-dirty"
fi

# Remote GitHub repo slug
REMOTE_URL=$(git config --get remote.origin.url)

# Extract GitHub slug: user/repo
if [[ $REMOTE_URL =~ github.com[:/](.+/.+?)(\.git)?$ ]]; then
    GH_SLUG="${BASH_REMATCH[1]}"
else
    GH_SLUG="unknown/repo"
fi

# GitHub links
COMMIT_URL="https://github.com/${GH_SLUG}/commit/$(git rev-parse HEAD)"
TAG_URL="https://github.com/${GH_SLUG}/releases/tag/${TAG}"

# Write LaTeX-safe metadata
cat <<EOF > header2.tex
% Auto-generated by make_header.sh
\usepackage{hyperref}
\newcommand{\commitsha}{\href{$COMMIT_URL}{\texttt{$SHA}}}
\newcommand{\branchname}{\texttt{$BRANCH}}
\newcommand{\commitdate}{\texttt{$DATE}}
\newcommand{\reponame}{\texttt{$GH_SLUG}}
\newcommand{\tagname}{\href{$TAG_URL}{\texttt{$TAG}}}
EOF
